paths:
    migrations: %%PHINX_CONFIG_DIR%%/private/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds
    context: ""

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        driver: pdo_mysql
        host: 127.0.0.1
        name: baryllium
        user: baryllium
        pass: baryllium
        port: 3306
        charset: utf8
        collation: utf8_general_ci

    development:
        adapter: mysql
        driver: pdo_mysql
        host: 127.0.0.1
        name: baryllium
        user: baryllium
        pass: baryllium
        port: 3306
        charset: utf8
        collation: utf8_general_ci
        
    testing:
        adapter: mysql
        driver: pdo_mysql
        host: 127.0.0.1
        name: baryllium-test
        user: baryllium
        pass: baryllium
        port: 3306
        charset: utf8
        collation: utf8_general_ci

system_mail_address: s3002591@rz.ba-dresden.de
version_order: creation
